"""add_new_field in roles as is_active

Revision ID: 39fee2d383ab
Revises: a56e692f812d
Create Date: 2026-01-22 06:54:38.607941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fee2d383ab'
down_revision: Union[str, Sequence[str], None] = 'a56e692f812d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.add_column('permissions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'is_active')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    # ### end Alembic commands ###
